language: ruby
bundler_args: --without=extras
script: rspec spec
rvm:
  - '1.9.2'
  - '1.9.3'
  - '2.0.0'
  - '2.1.2'
  - '2.2.2'
  - jruby
  - rbx-2
  ### ALLOWED FAILURES ###
  # see how compatible we are with dev versions, but do not fail the build
  - ruby-head
  - jruby-head
allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
